- hosts: all
  become: yes
  tasks:
  - name: install dkms
    apt: name=dkms

  - name: add apt-key  
    apt_key:
      url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
      state: present

  - name: add apt-key 
    apt_key:
      url: "https://www.virtualbox.org/download/oracle_vbox.asc"
      state: present

  - name: add apt-deb
    apt_repository:
      repo: deb http://download.virtualbox.org/virtualbox/debian xenial contrib
      state: present

  - name: install virtualbox-5.1
    apt:
      name: virtualbox-5.1
      state: present
      update_cache: yes





