- hosts: all
  become: yes
  tasks:
  - name: add apt-key  
    apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: present

  - name: add apt-deb
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
      state: present

  - name: install vscode
    apt:
      name: code
      state: present
      update_cache: yes





