- hosts: all
  become: yes
  tasks:
  - name: Install requiere-packages
    apt: pkg={{ item }} update_cache=yes state=present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: add apt-key 
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: add apt-deb
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial contrib
      state: present

  - name: install docker-ce
    apt:
      name: docker-ce
      state: present
      update_cache: yes
