# sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
# sudo add-apt-repository "deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/deb deb main"
# sudo apt-get update
# sudo apt-get install osquery
- hosts: all
  become: yes
  tasks:
  - name: add apt-key  
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B

  - name: add apt-deb
    apt_repository:
      repo: deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/deb deb main
      state: present

  - name: install osquery
    apt:
      name: osquery
      state: present
      update_cache: yes