- hosts: all
  become: yes
  user: '{{ user }}'
  tasks:
  - name: install linuxbrew
    apt: name=linuxbrew-wrapper

  - name: add bashrc / linuxbrew
    lineinfile: dest=/home/{{ user }}/.bashrc line="$HOME/.linuxbrew/bin:$PATH"
