homebrew_cask_packages:
  - name: adoptopenjdk
  - name: android-file-transfer
  - name: android-platform-tools
  - name: android-sdk
  - name: android-studio
  - name: dbeaver-community
  - name: docker
  - name: drawio
  - name: firefox
  - name: freecad
  - name: gimp
  - name: libreoffice
  - name: libreoffice-language-pack
  - name: macvim
  - name: osquery
  - name: postman
  - name: unetbootin
  - name: vagrant
  - name: virtualbox
  - name: visual-studio-code
  - name: wireshark
  - name: inkscape
